### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by protonhs** [hyan15/scrapy-proxy-pool#2]
Hello, 
I'm encountering this error lately:

File "/Users/mac/PycharmProjects/scrapy/venv/lib/python3.7/site-packages/proxyscrape/scrapers.py", line 164, in get_proxy_daily_http_proxies
    return _get_proxy_daily_proxies_parse_inner(centers[0], 'http', 'proxy-daily-http')
IndexError: list index out of range

any help please?

**Comment by sriramkumar1996** [comment]
Hi,
I've also encountered the same problem.
I think, their scraping algorithm for proxy list from some sources is outdated. Maybe due to website structural changes.

2019-07-25 09:18:29 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.xxxxx.com/>
Traceback (most recent call last):
  File "/home/srirambsk/Desktop/projects/my_env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/srirambsk/Desktop/projects/my_env/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/home/srirambsk/Desktop/projects/my_env/lib/python3.6/site-packages/scrapy_proxy_pool/middlewares.py", line 118, in process_request
    proxy = self.collector.get_proxy()
  File "/home/srirambsk/Desktop/projects/my_env/lib/python3.6/site-packages/proxyscrape/proxyscrape.py", line 408, in get_proxy
    self._refresh_resources(False)
  File "/home/srirambsk/Desktop/projects/my_env/lib/python3.6/site-packages/proxyscrape/proxyscrape.py", line 301, in _refresh_resources
    refreshed, proxies = resource['proxy-resource'].refresh(force)
  File "/home/srirambsk/Desktop/projects/my_env/lib/python3.6/site-packages/proxyscrape/scrapers.py", line 75, in refresh
    proxies = self._func()
  File "/home/srirambsk/Desktop/projects/my_env/lib/python3.6/site-packages/proxyscrape/scrapers.py", line 164, in get_proxy_daily_http_proxies
    return _get_proxy_daily_proxies_parse_inner(centers[0], 'http', 'proxy-daily-http')
IndexError: list index out of range

**Comment by sriramkumar1996** [comment]
In `/Users/mac/PycharmProjects/scrapy/venv/lib/python3.7/site-packages/proxyscrape/scrapers.py`, change the below functions:

```
def _get_proxy_daily_proxies_parse_inner(element, type, source):
    content = element.text
    rows = content.replace('"', '').replace("'", '').split('\n')
    proxies = set()
    for row in rows:
        row = row.strip()
        if len(row) == 0:
            continue

        params = row.split(':')
        params.extend([None, None, None, type, source])
        proxies.add(Proxy(*params))
    return proxies
```
```
def get_proxy_daily_http_proxies():
    url = 'http://www.proxy-daily.com'
    response = requests.get(url)
    if not response.ok:
        raise RequestNotOKError()

    try:
        soup = BeautifulSoup(response.content, 'html.parser')
        content = soup.find('div', {'id': 'free-proxy-list'})
        centers = content.find_all('div', {'class': 'centeredProxyList freeProxyStyle'})
        return _get_proxy_daily_proxies_parse_inner(centers[0], 'http', 'proxy-daily-http')
    except (AttributeError, KeyError):
        raise InvalidHTMLError()
```

**Comment by nealonhager** [comment]
@sriramkumar1996 that didn't work for me. However, in the same file if you go to RESOURCE_TYPE_MAP and comment out 'proxy-daily-http' that allows the whole program to work again.

**Comment by DenLakusta** [comment]
I had the same problem. After replacing functions, I have had another error. I'm not sure it will help you but in scrapers.py lib requests are not imported. 
import request works for me.

**Comment by longgangsima** [comment]
with change 

> In `/Users/mac/PycharmProjects/scrapy/venv/lib/python3.7/site-packages/proxyscrape/scrapers.py`, change the below functions:
> 
> ```
> def _get_proxy_daily_proxies_parse_inner(element, type, source):
>     content = element.text
>     rows = content.replace('"', '').replace("'", '').split('\n')
>     proxies = set()
>     for row in rows:
>         row = row.strip()
>         if len(row) == 0:
>             continue
> 
>         params = row.split(':')
>         params.extend([None, None, None, type, source])
>         proxies.add(Proxy(*params))
>     return proxies
> ```
> 
> ```
> def get_proxy_daily_http_proxies():
>     url = 'http://www.proxy-daily.com'
>     response = requests.get(url)
>     if not response.ok:
>         raise RequestNotOKError()
> 
>     try:
>         soup = BeautifulSoup(response.content, 'html.parser')
>         content = soup.find('div', {'id': 'free-proxy-list'})
>         centers = content.find_all('div', {'class': 'centeredProxyList freeProxyStyle'})
>         return _get_proxy_daily_proxies_parse_inner(centers[0], 'http', 'proxy-daily-http')
>     except (AttributeError, KeyError):
>         raise InvalidHTMLError()
> ```

this won't work, only  comment out 'PROXY_POOL_ENABLED = True', then it has no meaning to use proxy pool. anyone had solves this issues?

**Comment by miguelomp** [comment]
I install this repo from pip install git+ and looking for what dependencies it installed, there was **proxyscrape23** but in other project I had this repo work so I checked the dependencies in this other project and was installed **proxyscrape**

I changed proxyscrape23 to proxyscrape and now works
